### ISSUE TITLE
GSC incorrectly parses TOML

### ISSUE THREAD

**Issue by ratnadeepb** [gramineproject/gsc#12]
## Description of the problem
```
Exception: Cannot resolve "file:/usr/local/lib/python3.8/dist-packages/pandas/tests/io/data/legacy_pickle/1.2.4/empty_frame_v1_2_4-GH or the file does not exist.
```
when running 
```
sudo ./gsc sign-image <docker_name> enclave-key.pem
```

## Steps to reproduce

The issue won't reproduce on the current master branch. I am following up on [this](https://github.com/oscarlab/graphene/issues/2435) issue.
```
git clone http://github.com/oscarlab/graphene
cd graphene/Tools/gsc
cp config.yaml.template config.yaml
sed -i "s/2e737e69f076c60918f87d6829bb769925e75fec/a743b6a83b4f3587e1d72b53509239c21d3c1231/g" config.yaml
sudo apt install python3 python3-pip
sudo pip3 install docker jinja2 toml pyyaml

sudo ./gsc build --insecure-args <docker_name> ./test/ubuntu18.04-pytorch.manifest -nc --rm

openssl genrsa -3 -out enclave-key.pem 3072
sudo ./gsc sign-image <docker_name> enclave-key.pem
```

## Expected results
A signed copy of the container being created.

## Actual results
Fails with the following error:
```
Step 7/11 : RUN /graphene/python/graphene-sgx-sign         -libpal /graphene/Runtime/libpal-Linux-SGX.so         -key /gsc-signer-key.pem         -manifest /entrypoint.manifest         -output /entrypoint.manifest.sgx

 ---> Running in 3102aa0715d3
Attributes:
    size:        0x100000000
    thread_num:  32
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   0300000000000000
    misc_select: 00000000
    date:        2021-08-10
Trusted files:
Traceback (most recent call last):
  File "/graphene/python/graphene-sgx-sign", line 5, in <module>
    sys.exit(main())
  File "/graphene/python/graphenelibos/sgx_sign.py", line 851, in main
    return main_sign(args)
  File "/graphene/python/graphenelibos/sgx_sign.py", line 774, in main_sign
    for key, val in get_trusted_files(manifest).items():
  File "/graphene/python/graphenelibos/sgx_sign.py", line 242, in get_trusted_files
    targets[key] = (val, resolve_uri(val, check_exist))
  File "/graphene/python/graphenelibos/sgx_sign.py", line 211, in resolve_uri
    raise Exception(
Exception: Cannot resolve "file:/usr/local/lib/python3.8/dist-packages/pandas/tests/io/data/legacy_pickle/1.2.4/empty_frame_v1_2_4-GH or the file does not exist.

Removing intermediate container 3102aa0715d3
Failed to build a signed graphenized Docker image `<docker_name>`.
```

**Comment by aneessahib** [comment]
this can be closed now?

**Comment by dimakuv** [comment]
This issue was fixed by https://github.com/gramineproject/gsc/pull/26. Closing.
