### ISSUE TITLE
Conflicting dependency between Gramine and tensorflow-avx512 causing a deadlock in baremetal

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gsc#121]
## Description of the problem
Gramine dependency and tensorflow-avx512 dependency causing conflict in baremetal, unable to run tensorflow-avx512 with gramine in baremetal

When we install intel-tensorflow-avx512, MarkupSafe library is upgraded to 2.1.2 latest version,
If you run gramine-sgx-gen-private-key, it fails with "cannot import name 'soft_unicode' from 'markupsafe' ". The solution is to downgrade the MarkUpSafe to 2.0.1, when we downgrade, gramine-sgx-gen-private-key works, but tensorflow-avx512 get broken

When we run tensorflow-avx512, it returns with numpy error

## Steps to reproduce

1. python3 -m pip install intel-tensorflow-avx512 
2. Run gramine-sgx-gen-private-key -f

**gramine-sgx-gen-private-key -f**
```
Traceback (most recent call last):
  File "/home/gramineperf2/gramerf_framework/gramine_install/usr/bin/gramine-sgx-gen-private-key", line 11, in <module>
    from graminelibos import sgx_sign
  File "/home/gramineperf2/gramerf_framework/gramine_install/usr/lib/python3.8/site-packages/graminelibos/__init__.py", line 18, in <module>
    from .gen_jinja_env import make_env
  File "/home/gramineperf2/gramerf_framework/gramine_install/usr/lib/python3.8/site-packages/graminelibos/gen_jinja_env.py", line 7, in <module>
    import jinja2
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/gramineperf2/.local/lib/python3.8/site-packages/markupsafe/__init__.py)
```

## Expected results
tensorflow should be able to build and run inside Gramine

## Actual results
After running tensorflow-avx512
```
    import pandas as pd
../.local/lib/python3.8/site-packages/pandas/__init__.py:22: in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
../.local/lib/python3.8/site-packages/pandas/compat/__init__.py:18: in <module>
    from pandas.compat.numpy import (
../.local/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:23: in <module>
    raise ImportError(
E   ImportError: this version of pandas is incompatible with numpy < 1.20.3
E   your numpy version is 1.19.5.
E   Please upgrade numpy to >= 1.20.3 to use this pandas version
```

**Comment by anjalirai-intel** [comment]
Closing the issue. I will be raising this issue in gramine repo
