### ISSUE TITLE
Gramine Curated Application TOMLI error

### ISSUE THREAD

**Issue by shreejam21** [gramineproject/gsc#172]
```
unprotected-app.log: 

printing args util/curation_script.sh flask unprotected-app ubuntu:20.04 test y n verifier/ssl_common/ca.crt n y /home/shreejam/sgx-demo/db /home/shreejam/contrib/Intel-Confidential-Compute-for-X/mysecretkey

Generating signing key
Generating RSA private key, 3072 bit long modulus (2 primes)
...++++*........................................++++*........................................................................................................................................................................................................................................................................................++++*.........................................................................................................................................................................................................................................................++++*.........................................................++++
...........................++++*.++++
e is 3 (0x03)

DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  10.75kB
Step 1/2 : FROM unprotected-app
 ---> 70b3f98f0dd2
Step 2/2 : COPY ca.crt /
 ---> 21cc4ed876b5
Successfully built 21cc4ed876b5
Successfully tagged unprotected-app_x:latest

Cloning into 'gsc'...
Note: switching to 'c0be56daaa5a3a8a94f1b9c11a241100fec18b4b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Building unsigned graminized Docker image `gsc-unprotected-app_x-unsigned` from original application image `unprotected-app_x`...
**Traceback (most recent call last):
  File "./gsc", line 12, in <module>
    sys.exit(main(sys.argv))
  File "/home/shreejam/contrib/Intel-Confidential-Compute-for-X/gsc/./gsc.py", line 554, in main
    return args.command(args)
  File "/home/shreejam/contrib/Intel-Confidential-Compute-for-X/gsc/./gsc.py", line 251, in gsc_build
    user_manifest_dict = tomli.loads(user_manifest_contents)
  File "/home/shreejam/.local/lib/python3.8/site-packages/tomli/_parser.py", line 127, in loads
    raise suffixed_err(
tomli.TOMLDecodeError: Expected newline or end of document after a statement (at line 19, column 6)**

Error response from daemon: No such image: gsc-unprotected-app_x-unsigned:latest
Cannot find unsigned graminized Docker image `gsc-unprotected-app-unsigned`.
You must first build this image via `gsc build` command.
Error response from daemon: No such image: gsc-unprotected-app_x-unsigned:latest
Could not find graminized Docker image gsc-unprotected-app.
Please make sure to build the graminized image first by using 'gsc build' command.
```

## Description of the problem 
 I have a flask image and when I try to create/ build the gsc-protected flask image using curate.py script. I am getting a TOMLI Error  pasted above from .log file

**Comment by dimakuv** [comment]
@jkr0103 @aneessahib Do you know what happens here?

**Comment by jkr0103** [comment]
Seems like a manifest issue. Could you paste your manifest here?

**Comment by dimakuv** [comment]
@jkr0103 But this is for Curated Apps (aka [Intel® Confidential Compute for X](https://github.com/gramineproject/contrib/tree/master/Intel-Confidential-Compute-for-X#intel-confidential-compute-for-x)), if I read the description correctly.

And Curated Apps don't require a manifest file?

**Comment by jkr0103** [comment]
@shreejam21 have created new workload `flask` under workloads in curated apps and all the workloads have manifest template that template have the issue. Just debugged the issue with shrrejam21 and figured out that was indeed the manifest issue `sgx.max_threads = 512                   ]`

It's working now. @shreejam21 you may close the issue now.

Please create curated apps related issue in contrib repo: https://github.com/gramineproject/contrib/

**Comment by shreejam21** [comment]
Works Now. Thanks @jkr0103  for the swift response 👍. Closing Issue now
