### ISSUE TITLE
Cannot resolve /entrypoint.manifest 

### ISSUE THREAD

**Issue by p-vernaeckt** [gramineproject/gsc#67]
I've been waiting for #60 to be merged, and it seems that it introduces an issue dur to the fact that `entrypoint.manifest` was moved from `/` to `/gramine/app_files`.

Further details:
After wiping my local Docker images repo to start from scratch, I build a custom Ubutu-based image of NodeRed, then Gramininzed it:

```
./gsc build -c config.yaml --insecure-args b604f652bdea nodered.manifest  
```

Using [Dive](https://github.com/wagoodman/dive) I inspected it and [it looks like the file is actually there](https://ibb.co/MsV5WsC).

Signing, however, cannot find it:

```
ubuntu@sgx  ~/gsc  ./gsc sign-image b604f652bdea enclave-key.pem                                                               

Signing graminized Docker image `unsigned_image_name` -> `gsc-b604f652bdea`...
Step 1/6 : FROM gsc-b604f652bdea-unsigned as unsigned_image

 ---> 47dc02f98a1a
Step 2/6 : COPY gsc-signer-key.pem /gramine/app_files/gsc-signer-key.pem

 ---> 549ee88b74ce
Step 3/6 : RUN export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib -type d -path '*/site-packages')" && gramine-sgx-sign       --key /gramine/app_files/gsc-signer-key.pem       --manifest /gramine/app_files/entrypoint.manifest       --output /gramine/app_files/entrypoint.manifest.sgx

 ---> Running in 7dd953b572a7
Traceback (most recent call last):
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 74, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 34, in main
    expanded = manifest.expand_all_trusted_files()
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 175, in expand_all_trusted_files
    append_trusted_dir_or_file(trusted_files, tf, expanded)
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 56, in append_trusted_dir_or_file
    raise ManifestError(f'Cannot resolve {path}')
graminelibos.manifest.ManifestError: Cannot resolve /entrypoint.manifest

Removing intermediate container 7dd953b572a7
Failed to build a signed graminized Docker image `gsc-b604f652bdea`.
```

From here, it looks like [gramine-sgx-sign](https://github.com/gramineproject/gramine/blob/master/python/gramine-sgx-sign) cannot handle this change. Sorry I don't have enough time to dive in deeper.

**Comment by dimakuv** [comment]
Can you show your `nodered.manifest`? Maybe it contains `/entrypoint.manifest`?

Otherwise I don't know what the problem could be. Try to remove the `build/` directory under your GSC directory, and `docker prune` the images. It may be just a caching issue.

**Comment by p-vernaeckt** [comment]
Phew, it was that simple...Thanks you for your help!
