### ISSUE TITLE
Permission denied error during signing stage

### ISSUE THREAD

**Issue by p-vernaeckt** [gramineproject/gsc#68]
Hi.

I'me having an issue while signing an custom, non-root image in debug mode:

```
./gsc sign-image 4651f63e3c27 enclave-key.pem                                                                                                                                         master ●  07:09  07:43:52 

Signing graminized Docker image `unsigned_image_name` -> `gsc-4651f63e3c27`...
Step 1/6 : FROM gsc-4651f63e3c27-unsigned as unsigned_image

 ---> a54c6566fe5c
Step 2/6 : COPY gsc-signer-key.pem /gramine/app_files/gsc-signer-key.pem

 ---> 493eb743c8d6
Step 3/6 : RUN export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib -type d -path '*/site-packages')" && gramine-sgx-sign       --key /gramine/app_files/gsc-signer-key.pem       --manifest /gramine/app_files/entrypoint.manifest       --output /gramine/app_files/entrypoint.manifest.sgx

 ---> Running in 217a21c6ac85
Traceback (most recent call last):
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 74, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 34, in main
    expanded = manifest.expand_all_trusted_files()
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 175, in expand_all_trusted_files
    append_trusted_dir_or_file(trusted_files, tf, expanded)
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 70, in append_trusted_dir_or_file
    append_tf(trusted_files, uri, hash_file_contents(path))
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 29, in hash_file_contents
    with open(path, 'rb') as f:
PermissionError: [Errno 13] Permission denied: '/gramine/subprojects/packagecache/mbedtls-2.26.0.tar.gz'

Removing intermediate container 217a21c6ac85
Failed to build a signed graminized Docker image `gsc-4651f63e3c27`.
```

Indeed, the whole `/gramine/subprojects/packagecache/` folder's content has `600` permission with `0:0` UID/GID.

**Comment by dimakuv** [comment]
@p-vernaeckt https://github.com/gramineproject/gsc/pull/69 -- this should fix your problem.
